name: mlflow-telco-churn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - scikit-learn==1.5.1
      - pandas==2.2.2
      - numpy==1.26.4
      - matplotlib==3.9.0
      - seaborn==0.13.2